language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
install:
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest-cov
 - pip install .
script: 
 - pytest --cov-report=xml --cov=treebuilder tests/

after_success:
 - codecov -t $CODECOV_TOKEN

deploy:
  - provider: pypi
    user: __token__
    password: $FDIEULLE_PYPI_TOKEN
    distributions: "sdist bdist_wheel"
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      python: "3.9"
  - provider: release
    api_key: $GITHUB_TOKEN
    file: "dist/*"
    skip_cleanup: true
    on:
      tags: true
      python: "3.9"