language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
install:
 - pip install -r requirements.txt
 - pip install .
script: 
 - python -m unittest discover -v -s "./tests" -p "test_*.py"

 deploy:
  provider: pypi
  user: __token__
  password: $FDIEULLE_PYPI_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: staging